spring:
  application:
    name: AuthorizationServer
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_server
    username: admin
    password: secret
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/auth_server
    user: admin
    password: secret
    default-schema: auth_server
  jpa:
    properties:
      hibernate:
        default_schema: auth_server
        format_sql: true
    show-sql: true